server:
  AppVersion: 1.0.0
  Port: :8080
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

metrics:
  Url: 0.0.0.0:7070
  ServiceName: api